disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
# - colon
# - comma

included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
  # - BigoLive
excluded: # paths to ignore during linting. overridden by `included`.
  # - Carthage
  # - Pods
  # - Source/ExcludedFolder
  # - Source/ExcludedFile.swift

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

# parameterized rules can be customized from this configuration file
line_length: 300
# parameterized rules are first parameterized as a warning level, then error level.
type_body_length:
  - 300 # warning
  - 400 # error
# parameterized rules are first parameterized as a warning level, then error level.
variable_name_max_length:
  - 40 # warning
  - 60 # error
# parameterized rules are first parameterized as a warning level, then error level.
variable_name_min_length:
  - 3 # warning
  - 2 # error
